### ISSUE TITLE
请问为啥没使用TargetDataSource注解了

### ISSUE THREAD

**Issue by stormOH** [zonzie/read_write_separator_jpa#1]
首先非常感谢分享，项目让我对spring boot下的读写分离有了比较全面的认识理解，感谢！
    然后想问下，是基于什么考虑没有在切面使用TargetDataSource的注解区分数据源，而是换成了使用Transactional注解，用自己的注解会有什么问题吗？
    再次表示非常感谢！

**Comment by zonzie** [comment]
直接用切面判断的方法名,没用注解
